#!/bin/bash
LOCAL_RHINO_LOC=~/rhino_mount/
echo "ENTER PASSWORD TO YOUR COMPUTER:"
mkdir -p $LOCAL_RHINO_LOC
echo "ENTER RHINO USERNAME:"
read USERNAME
sshfs $USERNAME@rhino2.psych.upenn.edu:/ $LOCAL_RHINO_LOC -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,follow_symlinks,idmap=user -o volname=rhino_mount -o defer_permissions
echo "Drag the folder to the sidebar to create a shortcut..."
open $LOCAL_RHINO_LOC
